spring:
  application:
    name: currency-conversion-service

server:
  port: 8100

#currency-exchange-service:
#  ribbon:
#    listOfServers: localhost:8000, localhost:8001

eureka:
  client:
    service-url:
      default-zone: localhost:8761/eureka
