INSERT INTO EXCHANGE_VALUE(ID, SOURCE, "TARGET", CONVERSION_FACTOR, PORT) VALUES(UUID(), 'USD', 'IDR', 14509, 0)
INSERT INTO EXCHANGE_VALUE(ID, SOURCE, "TARGET", CONVERSION_FACTOR, PORT) VALUES(UUID(), 'USD', 'JPY', 110.37, 0)
INSERT INTO EXCHANGE_VALUE(ID, SOURCE, "TARGET", CONVERSION_FACTOR, PORT) VALUES(UUID(), 'USD', 'MYR', 4.19, 0)
