spring:
  application:
    name: config-server
  cloud:
    bus:
      enabled: true
    config:
      server:
        git:
          uri: file:///C:/git%20repo/udemy-spring-cloud-microservices-configurations/

server:
  port: 8888
